### ISSUE TITLE
Change socket for openlog()/syslog() fails

### ISSUE THREAD

**Issue by tfendin** [iqe/ld-preload-socket#1]
Hi
I'm trying to change which socket is opened (`connect()`) by standard c library function `openlog()`. Its socket is hardcoded to `/dev/log`, but for our system test suite I want to create a separate logfile for each test by using a modifed `rsyslogd`. I compiled this library to `libsyslog_interceptor.so`. When I start my testprogram it prints the mappings from the `setup()` function, so I'm pretty sure that I've successfully pre-loaded the library. But the call to `connect()` seems to go directly to the system call, it seems to bypass this library. Could this be because `openlog()` in glibc `syslog.c` calls `__connect()`? I've tried to change the name of `connect` to `__connect` in `ld-preload-socket.c` to no avail. Any help or pointers is appreciated.

```
$ LD_PRELOAD_SOCKET_UNIX_SOCK_MAP="/dev/log:/tmp/private-log" LD_PRELOAD=$PWD/libsyslog_interceptor.so ./openlog
LD_PRELOAD_SOCKET: 1 mappings defined for UNIX socket paths
LD_PRELOAD_SOCKET:    '/dev/log' -> '/tmp/private-log'
LD_PRELOAD_SOCKET: 0 mappings defined for INET socket ports
$
```

Source of openlog.c:
```c
#include <syslog.h>
#include <unistd.h>
int main(int argc, char *argv[])
{
  openlog(NULL, LOG_NDELAY|LOG_PID, LOG_LOCAL0);
  syslog(LOG_INFO, "My log message");
  usleep(1000);
  return 0;
}
```

**Comment by iqe** [comment]
I think you are right. `__connect` is defined as `libc_hidden_def (__connect)` in glibc's socket.c. Apparently this means it is internal to glibc and cannot be overwritten by LD_PRELOAD. (https://stackoverflow.com/a/21422495)

Maybe you can reconfigure rsyslogd to write different log files based on the PID of the caller or even something that's in the log messages? It is pretty flexible in this regard, as far as I remember.

**Comment by tfendin** [comment]
Thanks! That certainly explains why I couldn't get it to work.
Yes, I could reconfigure rsyslogd to suit my needs, it is indeed very flexible. But I don't want the user who runs the test suite to be forced to use escalated privileges, that's why I tumbled along the road which lead me to this repo :)
